### ISSUE TITLE
Evaluation of splitting algorithms

### ISSUE THREAD

**Issue by frenchfaso** [open-ortho/edu.case.BFD9000#8]
Evaluation of feasibility of classic image processing techniques for automatic splitting of TIFF scans.
The deliverable for this issue is a jupyter notebook testing the following classic algorithms for automatic splitting:
- Hough lines detection
- ...

**Comment by zgypa** [comment]
@frenchfaso  finished this. He told me that future work is listed in the documentation (the notebook) itself.
